### ISSUE TITLE
A lot of exceptions in Rider 2022.2 EAP*

### ISSUE THREAD

**Issue by mfilippov** [Abc-Arbitrage/Abc.MoqComplete#30]
Rider and R# 2022.2 contains breaking API change. Which produce a lot of exceptions when MoqComplete installed.
I will prepare fix for that issue.
```
--- EXCEPTION #1/2 [TypeLoadException]
Message = “Could not load type 'JetBrains.ReSharper.Psi.ITypeEx' from assembly 'JetBrains.ReSharper.Psi, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325'.”
ExceptionPath = Root.InnerException
ClassName = System.TypeLoadException
HResult = COR_E_TYPELOAD=80131522
Source = Abc.MoqComplete.Rider
TypeLoadClassName = JetBrains.ReSharper.Psi.ITypeEx
TypeLoadAssemblyName = “JetBrains.ReSharper.Psi, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
TypeLoadResourceID = -2146233054
StackTraceString = “
  at Abc.MoqComplete.CompletionProvider.ItIsAny.BaseItIsAnyParameterProvider.AddLookupItems(CSharpCodeCompletionContext context, IItemsCollector collector)
     at JetBrains.Util.Logging.Logger.CatchIgnoreException[TValue,TException](Func`1 F, TValue defaultValue)
”
```

**Comment by lconstan** [comment]
fixed in #31.

Thanks for the PR

**Comment by mfilippov** [comment]
@lconstan Could you deploy a new version of plugin with fix? We are receiving a lot of feedback about this issue.

**Comment by lconstan** [comment]
@mfilippov I've queued a new version yesterday when the PR merged for both R# and Rider
